# Generated by Django 4.2.6 on 2024-01-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_labtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtask',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
