# Generated by Django 4.2.6 on 2024-01-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_labtask_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtask',
            name='team',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='labtask',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
