# Generated by Django 4.2.6 on 2024-01-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_labtask_team_labtask_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtask',
            name='team',
        ),
        migrations.AddField(
            model_name='labtask',
            name='team',
            field=models.ManyToManyField(null=True, to='myapp.projectroom'),
        ),
    ]
