# Generated by Django 4.2.6 on 2024-01-11 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_labtask_file_remove_labtask_team_labfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labfile',
            name='lab_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.labtask'),
        ),
        migrations.AlterField(
            model_name='labfile',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projectroom'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('lab_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.labfile')),
            ],
        ),
    ]
