# Generated by Django 4.2.6 on 2024-01-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.projectroom'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Done', 'Done')], default='Ongoing', max_length=10),
        ),
    ]
