# Generated by Django 4.2.6 on 2024-01-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_task_room_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectroom',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
