# Generated by Django 5.0.6 on 2024-06-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_projectroom_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='./media'),
        ),
    ]
